In [4]:
import pandas as pd
import numpy as np

data = pd.read_csv("../data/processed/data_lpa.csv")

data.head()

,Jenis Kelamin,Semester saat ini,Angkatan,Departemen,Program Studi,WB1,WB2,WB3,WB4,WB5,...,WB_Score,ACD_Score,SOC_Score,CAR_Score,Profile,Profile_1_Prob,Profile_2_Prob,Profile_3_Prob,Profile_4_Prob,Profile_5_Prob
0,Laki-laki,Semester 5,2024,Departemen Teknik Elektro (DTE),S. Tr. Teknik Elektro Industri,4,4,3,3,3,...,3.666667,3.250,4.000,3.125,3,7.344124e-02,6.986308e-03,9.195725e-01,6.477571e-32,0.0
1,Perempuan,Semester 3,2025,Departemen Teknologi Multimedia Kreatif (DTMK),D3 Teknologi Multimedia dan Broadcasting,1,4,1,2,1,...,2.666667,2.875,3.375,1.250,4,1.960853e-21,4.047098e-08,1.437590e-03,9.985624e-01,0.0
2,Laki-laki,Semester 5,2024,Departemen Teknik Informatika dan Komputer (DTIK),S.Tr. Teknik Informatika,3,4,4,4,2,...,3.444444,3.375,3.375,2.750,3,3.992003e-10,1.141044e-03,9.988590e-01,1.592320e-16,0.0
3,Laki-laki,Semester 5,2024,Departemen Teknik Informatika dan Komputer (DTIK),S.Tr. Sains Data Terapan,3,4,4,3,4,...,3.555556,3.750,3.750,3.375,3,1.243515e-02,1.326088e-01,8.549560e-01,2.066304e-30,0.0
4,Laki-laki,Semester 5,2024,Departemen Teknik Informatika dan Komputer (DTIK),D3 Teknik Informatika,3,2,4,4,3,...,2.777778,3.500,4.750,1.125,1,9.999999e-01,1.215510e-08,2.350848e-08,3.864741e-08,0.0

In [5]:
profile_count = data["Profile"].value_counts().sort_index()

profile_count

Profile
1    14
2    27
3    57
4     8
5    13
Name: count, dtype: int64

In [6]:
profile_percentage = (
    data["Profile"]
    .value_counts(normalize=True)
    .sort_index()
    .mul(100)
    .round(2)
)

profile_percentage

Profile
1    11.76
2    22.69
3    47.90
4     6.72
5    10.92
Name: proportion, dtype: float64

In [7]:
score_cols = [
    "WB_Score",
    "ACD_Score",
    "SOC_Score",
    "CAR_Score"
]

profile_summary = (
    data.groupby("Profile")[score_cols]
    .mean()
    .round(2)
)

profile_summary

         WB_Score  ACD_Score  SOC_Score  CAR_Score
Profile
1            2.85       2.94       4.10       3.34
2            4.06       3.88       4.25       3.65
3            3.13       3.12       3.70       3.05
4            2.11       2.31       2.41       1.77
5            4.48       4.52       5.00       4.02

In [11]:
profile_distribution = (
    data["Profile"]
    .value_counts()
    .sort_index()
    .to_frame("Jumlah")
)

profile_distribution["Persentase"] = (
    profile_distribution["Jumlah"]
    / len(data)
    * 100
).round(2)

profile_distribution

         Jumlah  Persentase
Profile
1            14       11.76
2            27       22.69
3            57       47.90
4             8        6.72
5            13       10.92

In [12]:
angkatan_profile = pd.crosstab(
    data["Profile"],
    data["Angkatan"],
    normalize="index"
).mul(100).round(2)

angkatan_profile

Angkatan   2023   2024   2025   2026
Profile
1          7.14  28.57  14.29  50.00
2          0.00  25.93  11.11  62.96
3          1.75  21.05  35.09  42.11
4         12.50   0.00  75.00  12.50
5          7.69   7.69   0.00  84.62

In [13]:
prodi_profile = pd.crosstab(
    data["Profile"],
    data["Program Studi"],
    normalize="index"
).mul(100).round(2)

prodi_profile

Program Studi,D3 Teknik Elektro Industri,D3 Teknik Elektronika,D3 Teknik Informatika,D3 Teknologi Multimedia dan Broadcasting,S. Tr. Teknik Elektro Industri,S.Tr. Bisnis Digital,S.Tr. Sains Data Terapan,S.Tr. Sistem Pembangkit Energi,S.Tr. Teknik Elektronika,S.Tr. Teknik Informatika,S.Tr. Teknik Komputer,S.Tr. Teknik Mekatronika,S.Tr. Teknik Telekomunikasi,S.Tr. Teknologi Game,S.Tr. Teknologi Rekayasa Internet,S.Tr. Teknologi Rekayasa Keselamatan K3,S.Tr. Teknologi Rekayasa Multimedia,S.Tr. Teknologi Rekayasa Perancangan Manufaktur
Profile,,,,,,,,,,,,,,,,,,
1,14.29,7.14,7.14,0.00,7.14,0.00,7.14,0.00,14.29,0.00,14.29,0.00,0.00,7.14,7.14,7.14,0.00,7.14
2,11.11,7.41,7.41,7.41,3.70,0.00,25.93,0.00,0.00,7.41,7.41,7.41,0.00,7.41,3.70,0.00,0.00,3.70
3,1.75,3.51,1.75,5.26,3.51,3.51,26.32,7.02,5.26,5.26,5.26,10.53,5.26,1.75,7.02,0.00,5.26,1.75
4,0.00,0.00,0.00,12.50,0.00,0.00,0.00,0.00,25.00,12.50,0.00,12.50,0.00,12.50,25.00,0.00,0.00,0.00
5,7.69,7.69,7.69,7.69,7.69,0.00,15.38,7.69,7.69,7.69,7.69,0.00,0.00,7.69,7.69,0.00,0.00,0.00

In [14]:
profile_summary.to_csv(
    "../data/output/cluster_profile.csv"
)

print("Analisis profile berhasil disimpan.")

Analisis profile berhasil disimpan.