In [2]:
import pandas as pd
import numpy as np

data = pd.read_csv("../data/processed/data_clean.csv")

data.head()

,Jenis Kelamin,Semester saat ini,Angkatan,Departemen,Program Studi,WB1,WB2,WB3,WB4,WB5,...,SOC7,SOC8,CAR1,CAR2,CAR3,CAR4,CAR5,CAR6,CAR7,CAR8
0,Laki-laki,Semester 5,2024,Departemen Teknik Elektro (DTE),S. Tr. Teknik Elektro Industri,4,4,3,3,3,...,4,4,3,3,3,3,3,4,3,3
1,Perempuan,Semester 3,2025,Departemen Teknologi Multimedia Kreatif (DTMK),D3 Teknologi Multimedia dan Broadcasting,1,4,1,2,1,...,3,3,2,1,2,1,1,1,1,1
2,Laki-laki,Semester 5,2024,Departemen Teknik Informatika dan Komputer (DTIK),S.Tr. Teknik Informatika,3,4,4,4,2,...,3,3,1,3,4,2,3,4,3,2
3,Laki-laki,Semester 5,2024,Departemen Teknik Informatika dan Komputer (DTIK),S.Tr. Sains Data Terapan,3,4,4,3,4,...,4,3,4,4,4,2,3,3,3,4
4,Laki-laki,Semester 5,2024,Departemen Teknik Informatika dan Komputer (DTIK),D3 Teknik Informatika,3,2,4,4,3,...,4,5,1,1,2,1,1,1,1,1

In [3]:
wb_cols = [f"WB{i}" for i in range(1, 10)]
acd_cols = [f"ACD{i}" for i in range(1, 9)]
soc_cols = [f"SOC{i}" for i in range(1, 9)]
car_cols = [f"CAR{i}" for i in range(1, 9)]

print("WB  :", wb_cols)
print("ACD :", acd_cols)
print("SOC :", soc_cols)
print("CAR :", car_cols)

WB  : ['WB1', 'WB2', 'WB3', 'WB4', 'WB5', 'WB6', 'WB7', 'WB8', 'WB9']
ACD : ['ACD1', 'ACD2', 'ACD3', 'ACD4', 'ACD5', 'ACD6', 'ACD7', 'ACD8']
SOC : ['SOC1', 'SOC2', 'SOC3', 'SOC4', 'SOC5', 'SOC6', 'SOC7', 'SOC8']
CAR : ['CAR1', 'CAR2', 'CAR3', 'CAR4', 'CAR5', 'CAR6', 'CAR7', 'CAR8']

In [4]:
data["WB_Score"] = data[wb_cols].mean(axis=1)
data["ACD_Score"] = data[acd_cols].mean(axis=1)
data["SOC_Score"] = data[soc_cols].mean(axis=1)
data["CAR_Score"] = data[car_cols].mean(axis=1)

data[
    ["WB_Score", "ACD_Score", "SOC_Score", "CAR_Score"]
].head()

   WB_Score  ACD_Score  SOC_Score  CAR_Score
0  3.666667      3.250      4.000      3.125
1  2.666667      2.875      3.375      1.250
2  3.444444      3.375      3.375      2.750
3  3.555556      3.750      3.750      3.375
4  2.777778      3.500      4.750      1.125

In [5]:
score_cols = [
    "WB_Score",
    "ACD_Score",
    "SOC_Score",
    "CAR_Score"
]

print(data[score_cols].describe())

         WB_Score   ACD_Score   SOC_Score   CAR_Score
count  119.000000  119.000000  119.000000  119.000000
mean     3.388422    3.369748    3.926471    3.237395
std      0.773444    0.734190    0.738867    0.859640
min      1.333333    1.625000    1.750000    1.125000
25%      2.777778    3.000000    3.500000    2.750000
50%      3.333333    3.375000    4.000000    3.125000
75%      4.000000    3.875000    4.375000    3.875000
max      5.000000    5.000000    5.000000    5.000000

In [6]:
data.to_csv(
    "../data/processed/data_scored.csv",
    index=False
)

print("Data scoring berhasil disimpan.")
print("Shape:", data.shape)

Data scoring berhasil disimpan.
Shape: (119, 42)